# Generated by Django 4.1.13 on 2024-01-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date published")),
                ("invoice_number", models.CharField(max_length=10)),
                ("value", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "haircut_percentage",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "daily_fee_percentage",
                    models.DecimalField(decimal_places=5, max_digits=10),
                ),
                ("currency", models.CharField(max_length=10)),
                ("revenue_source", models.CharField(max_length=40)),
                ("customer", models.CharField(max_length=40)),
                (
                    "expected_payment_duration",
                    models.IntegerField(help_text="number of days until payment"),
                ),
            ],
        ),
    ]
