# Generated by Django 4.1.13 on 2024-01-05 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dataIngestion", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invoice",
        ),
    ]
